language: node_js
node_js:
  - 8
dist: trusty
sudo: required
addons:
  chrome: stable
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
services:
  - mongodb
  - redis-server
env:
  - NODE_ENV=ci
  - PORT=3000
cache:
  directories:
    - node_modules
    - client/node_modules
install:
  - npm i
  - npm run build
script:
  - nohup npm start &
  - sleep 3
  - npm test
